[package]
name = "blox-football-league/awards"
description = ""
version = "0.1.0"
license = ""
authors = [
    "Nicklaus-s",
    "metricsrbx"
]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
server-packages = "game.ServerScriptService.Packages"

[dependencies]
Knit = "sleitnick/knit@1.5.1"
Trove = "sleitnick/trove@1.0.0"
Signal = "sleitnick/signal@1.3.0"
EnumList = "sleitnick/enum-list@2.0.1"
TableUtil = "sleitnick/table-util@1.2.0"

Fusion = "elttob/fusion@0.2.0"

Promise = "evaera/promise@4.0.0"
Sift = "csqrl/sift@0.0.5"

t = "osyrisrblx/t@3.0.0"
